# Generated by Django 4.1.3 on 2023-01-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=150)),
                ('contact_method', models.CharField(max_length=20, verbose_name='Contact')),
                ('enquiry_info', models.CharField(max_length=50, verbose_name='About your enquiry...')),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
    ]
