# Generated by Django 4.1.3 on 2023-01-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Client Message', 'verbose_name_plural': 'Client Messages'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='enquiry_info',
            field=models.CharField(max_length=50, verbose_name='Enquiry Info'),
        ),
    ]
