# Generated by Django 4.1.3 on 2022-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_meta_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AlterField(
            model_name='product',
            name='year_of_release',
            field=models.IntegerField(),
        ),
    ]
