# Generated by Django 4.1.3 on 2022-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_rating_alter_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year_of_release',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
