# Generated by Django 4.1.3 on 2022-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_year_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='developer',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
